version: "3.9"
   
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: Eddie
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  web:    
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: Eddie
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - db